repository: https://github.com/Simple-Observability/simob-agent
documentation: https://simpleobservability.com/docs/installation
homepage: https://simpleobservability.com
issues: https://github.com/Simple-Observability/simob-agent/issues
