version: "2"

run:
  tests: false

linters:
  exclusions:
    generated: lax
    paths:
      - thirdparty/go-diskqueue
    rules:
      - source: '^\s*defer .*\.Close\(\)$'
        linters:
          - errcheck
